Store requests inside ~/.chatgpt.d
. When I make a request, I need a method to specify a system prompt,
  temperature, model name, possibly other options. I can think of three
  approaches.

  1. Specify everything in the file, such as:

     ```
     {"model":"gpt-3.5-turbo","temperature":0.8}

     system

     ^Isystem instructions

     user

     ^Iuser input
     ```

     I admin, this is ugly. However, it's consistent with the idea
     "file = chat".

     It can be argued that API options are not as important to preserve as
     the conversation itself. In the case of an unproductive conversation,
     it is more effective to rewrite or remove it rather than keeping it and
     using options to replicate the earlier, unsuccessful, requests.

  2. Keeping the conversation, including system instructions, in a file
     and specifying API options in the command-line interface.

  3. Treating system instructions as API options and specifying them
     together in a configuration file.

. Note that the second and third approaches are compatible with each
  other. System instructions can be omitted in the configuration, but
  specified in the chat. Options specified in the command-line arguments
  override those configured in a configuration file.

. The question is which method to choose and why. I have found it very
  convenient to make requests to OpenAI without any dedicated workflow,
  simply by running `chatgpt-here proofread`. It is easy to access
  and automatize. I have used it around a hundred times while editing
  this message.

  I still use the dedicated workflow for ChatGPT on my computer because
  it's good for extended conversations. In this situation, I use a
  minimal configuration file, set "system" instructions in the chat,
  and set API options using command-line arguments.

diff --git a/chatgpt b/chatgpt
--- a/chatgpt
+++ b/chatgpt
@@ -2,16 +2,13 @@
 
 set -o errexit -o nounset -o pipefail
 
-build_request() {
-	local file
-	file="$(mktemp)"
+die() {
+	printf '%s\n' "$*" >&2
+	exit 1
+}
 
-	cat >"$file" <<-'EOF'
-		{
-			"model": "gpt-3.5-turbo",
-			"n": 1
-		}
-	EOF
+build_request() {
+	local file="$1"
 
 	_add_message() {
 		local role="$1" content="$2"
@@ -43,10 +40,11 @@ build_request() {
 	if [[ "$role" ]]; then
 		_add_message "$role" "$content"
 	fi
-
-	cat -- "$file"
-	rm -- "$file"
 }
+
+#
+# configuration
+#
 
 CURL=(/usr/bin/curl --silent --fail)
 
@@ -54,16 +52,52 @@ if rc="$HOME/.chatgptrc"; [[ -f "$rc" && -r "$rc" ]]; then
 	source -- "$rc"
 fi
 
-request="$(mktemp)" response="$(mktemp)"
-trap 'rm -- "$request" "$response"' EXIT
+#
+# resource cleanup
+#
 
-build_request >"$request"
+cleanup_files=()
+trap 'rm -f -- "${cleanup_files[@]}"' EXIT
+
+#
+# command-line args
+#
+
+if (( $# < 1 )); then
+	die 'invalid usage'
+fi
+
+#
+# handle base_request
+#
+
+base_request="$(mktemp)"
+cleanup_files+=("$base_request")
+
+if ! "$HOME/.chatgpt.d/$1" >"$base_request"; then
+	die 'base request is broken'
+fi
+
+#
+# build the real request and send it
+#
+
+request="$(mktemp)" response="$(mktemp)"
+cleanup_files+=("$request" "$response")
+
+cat -- "$base_request" >"$request"
+
+build_request "$request"
 
 "${CURL[@]}" \
 	-H "Authorization: Bearer $OPENAI_API_KEY" \
 	--json "@$request" \
 	'https://api.openai.com/v1/chat/completions' \
 >"$response"
+
+#
+# print the response
+#
 
 printf '\n'
 
